chore: update build config

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,15 +1,19 @@
 #!/bin/sh
-
-# Protect master/main from direct pushes.
 BRANCH=$(git rev-parse --abbrev-ref HEAD)
-PROTECTED_BRANCHES="master main"
+PROTECTED="master main"
 
-echo "\n===\n>> Running in shell:: $SHELL"
-echo ">> Pre-push Hook:: Checking BRANCH: $BRANCH\n===\n"
-
-for protected in $PROTECTED_BRANCHES; do
-    if [ "$BRNCH" = "$protected" ]; then
-        echo "\n🚫 Push directly to BRANCH: $BRANCH is not allowed!\n"
+for protected in $PROTECTED; do
+    if [ "$BRANCH" = "$protected" ]; then
+        echo "🛑 ERROR: Direct push to '$BRANCH' is disabled."
+        echo "💡 SOLUTION: Create a new branch (e.g., 'feat/update-login')."
         exit 1
     fi
 done
+
+# Regex: Allow only lowercase, numbers, and dashes
+if ! echo "$BRANCH" | grep -qE '^[a-z0-9/-]+$'; then
+    echo "🛑 ERROR: Branch name '$BRANCH' is invalid."
+    echo "💡 SOLUTION: Rename branch using only lowercase letters and dashes."
+    exit 1
+fi
+exit 0
